### ISSUE TITLE
No module named 'haiku'

### ISSUE THREAD

**Issue by tcbegley** [Information-Fusion-Lab-Umass/NuX#1]
Hello,

I was interested to try this library out and run your example notebooks, but I'm running into problems due to not having the `haiku` module installed. I can't find this on PyPI, is it a publicly available module?

I tried installing from source on the `nohaiku` branch but it seems it still has references to haiku that cause the code to fail.

**Comment by EddieCunningham** [comment]
Hi, thanks for the interest!  You can install Haiku with the pip install listed [here](https://github.com/deepmind/dm-haiku#installation).  Also make sure to use the master branch of this repo because it has the most recent implementations of everything.

**Comment by tcbegley** [comment]
Great, managed to get the code running, thanks!

Would be helpful if there was a `requirements.txt` or similar to get all the dependencies (I was also missing `chex`, and `optax`).
