### ISSUE TITLE
README example not working

### ISSUE THREAD

**Issue by MilesCranmer** [Information-Fusion-Lab-Umass/NuX#3]
Hi,

Trying this package out as I search for a Flows package in JAX.

I tried the README example but it looks like the Coupling layer moved:
```python
>> import nux
>> nux.Coupling()
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-1f67c7aa3b7f> in <module>
----> 1 nux.Coupling()

AttributeError: module 'nux' has no attribute 'Coupling'
```

What is the updated name for this?

Cheers,
Miles

**Comment by MilesCranmer** [comment]
It looks like it was removed altogether in 7d3a00b1702dbfe60709238d3ccc439e74118c02, and the base class was replaced with `Elementwise`. Is this correct?

<img width="587" alt="Screen Shot 2021-03-17 at 1 36 39 PM" src="https://user-images.githubusercontent.com/7593028/111512138-cf83e780-8725-11eb-89d7-1e79a0c912ec.png">

I tried to naively replace `Coupling` with `flows.Elementwise` in the README example but now it gives me this error:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-28-c64bc68e8a86> in <module>
      6     )
      7 
----> 8 flow = nux.Flow(create_flow, key,
      9                 train_inputs, batch_axes=(0,))

~/miniconda3/envs/eft_gnn/lib/python3.8/site-packages/nux/internal/flow.py in __init__(self, create_fun, key, inputs, batch_axes, check_for_bad_init, **kwargs)
     30 
     31     self._flow = transform_flow(create_fun)
---> 32     self.params, self.state, outputs = self._flow.init(key,
     33                                                        inputs,
     34                                                        batch_axes=batch_axes,

~/miniconda3/envs/eft_gnn/lib/python3.8/site-packages/nux/internal/transform.py in init_fn(rng, inputs, batch_axes, return_initial_output, **kwargs)
     92     with new_custom_context(rng=rng) as ctx:
     93       # Create the model
---> 94       model = create_fun()
     95 
     96       # Load the batch axes for the inputs

<ipython-input-28-c64bc68e8a86> in create_flow()
      1 def create_flow():
      2     return nux.sequential(
----> 3         nux.flows.Elementwise(),
      4         nux.AffineLDU(),
      5         nux.UnitGaussianPrior()

~/miniconda3/envs/eft_gnn/lib/python3.8/site-packages/haiku/_src/module.py in __call__(cls, *args, **kwargs)
    130     # NOTE: We disable pytype since (somewhat surprisingly) this method is bound
    131     # with the new class and not the metaclass.
--> 132     module = cls.__new__(cls, *args, **kwargs)  # pytype: disable=wrong-arg-types
    133 
    134     # Now attempt to initialize the object.

TypeError: Can't instantiate abstract class Elementwise with abstract methods get_out_shape, transform
```

**Comment by EddieCunningham** [comment]
Hi, thanks for the interest in NuX!  You are correct, that was removed.  Elementwise is the base class that classes that use coupling like [logistic cdf mixture](https://github.com/Information-Fusion-Lab-Umass/NuX/blob/23b53cf897e4b15074ecd893c03915bc10511ec0/nux/flows/bijective/logistic_cdf_mixture.py#L315), [real nvp](https://github.com/Information-Fusion-Lab-Umass/NuX/blob/23b53cf897e4b15074ecd893c03915bc10511ec0/nux/flows/bijective/real_nvp.py#L16) and [neural spline](https://github.com/Information-Fusion-Lab-Umass/NuX/blob/23b53cf897e4b15074ecd893c03915bc10511ec0/nux/flows/bijective/spline.py#L134) inherit from.  If you replace the old coupling layer with these then it should work.  Sorry for leaving the old code in the readme, I'll put a working example in later today. 

As you try NuX out, please let me know if you have any feedback.  NuX has an ever-growing list of layers/features that I use in my own research that I hope ends up being useful to others too.  If you would like to see any specific layer implementations, examples or documentation let me know and I can code that up.

**Comment by MilesCranmer** [comment]
Awesome, thanks - will try those classes!

Thanks, sounds great, I will let you know.

Cheers,
Miles

**Comment by MilesCranmer** [comment]
By the way, for discussing features/general questions , what do you think about enabling the "Discussions" part of the GitHub repo? (Settings->Options->Features->Discussions (click the checkmark)). I have some pretty general questions (about training a flow as part of a larger Haiku model), but it seems like an open-ended discussion board might be better. What do you think?

**Comment by EddieCunningham** [comment]
Sure thing, I just enabled discussions
